sudo: required

services: 
  - docker

before_install:
  - docker build -t sysadmin-exe/reactlab -f Dockerfile.dev .

script:
  - docker run sysadmin-exe/reactlab npm run test -- --coverage

after_success:
  - docker build -t sysadminexe/reactlab .
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to docker hub
  - docker push sysadminexe/reactlab
  

